language: java

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  - PROJECT_DIR=FindPairs

before_install: cd $PROJECT_DIR

after_script: gradlew createJar
